<?php
/**
 *
 * $Id: default.php 1.0.0 2011-12-04 22:00:52 Quang Long $
 * @package	    Commemorativeairforce 
 * @subpackage	Flash Slide Show
 * @version     1.0.0
 * @description 
 * @copyright	  Copyright © 2011 - All rights reserved.
 * @license		  GNU General Public License v2.0
 * @author		  Quang Long
 * @author mail	quanglong05@gmail.com
 * @website		  epiphanydev.com
 *
 * CODE GENERATED BY: ALEXEY GORDEYEV IK CODE GENERATOR
 * HTTP://WWW.AGJOOMLA.COM/
 *
 *
 */

// no direct access
defined( '_JEXEC' ) or die( 'Restricted access' );
ini_set('display_errors',1);
	error_reporting(E_ALL);
$path_flash = '/images/banners/';
?>

<script type="text/javascript">
$(document).ready(function() {
    $('.flash_slideshow').cycle({
		fx: 'fade' // choose your transition type, ex: fade, scrollUp, shuffle, etc...
	});
});
</script>

<!-- START Flash Slide Show MODULE -->
<div class="flash_slideshow">
   <?php foreach($items as $item => $value) {   ?>
        <a href="<?php echo $value->clickurl ?>">
        <?php	
//                var_dump($value);
//                $width = $value->params->get('width');
//                $height = $value->params->get('height');
                $images = explode(",", $value->params);
                $imagepath = explode(":", $images[0]);
                $path = str_replace(array("\"", "\\"), "", $imagepath[1]);
                echo "<img src='".$path."' width = '1000px' height ='290px;' />";
        ?>
        </a>
    <?php } ?> 
</div>
<!-- END Flash Slide Show MODULE -->