<?php
/**
 *
 * $Id: mod_flashslideshow.php 1.0.0 2011-12-04 22:00:52 Quang Long $
 * @package	    Commemorativeairforce 
 * @subpackage	Flash Slide Show
 * @version     1.0.0
 * @description 
 * @copyright	  Copyright © 2011 - All rights reserved.
 * @license		  GNU General Public License v2.0
 * @author		  Quang Long
 * @author mail	quanglong05@gmail.com
 * @website		  epiphanydev.com
 *
 * CODE GENERATED BY: ALEXEY GORDEYEV IK CODE GENERATOR
 * HTTP://WWW.AGJOOMLA.COM/
 *
 *
 */

// no direct access
defined( '_JEXEC' ) or die( 'Restricted access' );
 
// include the helper file
require_once(dirname(__FILE__).DS.'helper.php');
 
/**
 * Example to get a parameter from the module's configuration
 * $chanelCount = $params->get('chanelcount');
 */



$items = ModFlashslideshowHelper::getItems();

 
// include the template for display
require(JModuleHelper::getLayoutPath('mod_flashslideshow'));

?>